SystemOrganization addCategory: #'Mongo-Queries'!
SystemOrganization addCategory: 'Mongo-Queries-Base'!
SystemOrganization addCategory: 'Mongo-Queries-Building'!
SystemOrganization addCategory: 'Mongo-Queries-Exceptions'!
SystemOrganization addCategory: 'Mongo-Queries-Nodes-Conditions'!
SystemOrganization addCategory: 'Mongo-Queries-Nodes-Other'!
SystemOrganization addCategory: 'Mongo-Queries-Queries'!
SystemOrganization addCategory: 'Mongo-Queries-Utilities'!
