SystemOrganization addCategory: #'Mongo-Client'!
SystemOrganization addCategory: #'Mongo-Client-Announcements'!
SystemOrganization addCategory: #'Mongo-Client-Client'!
SystemOrganization addCategory: #'Mongo-Client-Errors'!
SystemOrganization addCategory: #'Mongo-Client-ReadPreferences'!
SystemOrganization addCategory: #'Mongo-Client-Topology'!
SystemOrganization addCategory: #'Mongo-Client-Utilities'!
